export const GRID_ITEMS = [
  {
    id: 1,
    type: "large" as const,
    title: "Sistemas integrados sob medida",
    description: "Velocidade sem atalhos",
    className: "col-span-1 md:col-span-3 min-h-[280px] lg:min-h-[320px]",
    imgClassName: "object-contain h-full opacity-90",
    img: "/illustrations/SIAN-PRINT.png",
    imgWidth: 600,
  },
  {
    id: 2,
    type: "small" as const,
    title: "Processo claro, prazos reais e zero surpresas no final",
    description: "Processo transparente",
    className: "col-span-1 min-h-[280px]",
    imgClassName: "opacity-80",
    img: "/illustrations/02-journey.svg",
    imgWidth: 280,
  },
  {
    id: 3,
    type: "small" as const,
    title: "Arquitetura que escala conforme seu negócio cresce",
    description: "Qualidade de verdade",
    className: "col-span-1 min-h-[280px]",
    imgClassName: "opacity-80",
    img: "/illustrations/03-modules.svg",
    imgWidth: 280,
  },
  {
    id: 4,
    type: "small" as const,
    title: "Sem intermediários — você fala direto com quem constrói",
    description: "Comunicação direta",
    className: "col-span-1 min-h-[280px]",
    imgClassName: "opacity-80",
    img: "/illustrations/04-stack.svg",
    imgWidth: 280,
  },
];
