export const GRID_ITEMS = [
  {
    id: 1,
    type: "large" as const,
    title: "Transformamos desafios complexos em produtos digitais elegantes",
    description: "Estúdio de produto completo",
    className: "col-span-1 md:col-span-3 min-h-[350px] lg:min-h-[420px]",
    imgClassName: "object-contain h-full opacity-90",
    img: "/illustrations/SIAN-PRINT.png",
    imgWidth: 600,
  },
  {
    id: 2,
    type: "small" as const,
    title: "Da descoberta ao lançamento — dominamos todo o ciclo de entrega",
    description: "Sem lacunas. Sem repassos.",
    className: "col-span-1 min-h-[280px]",
    imgClassName: "opacity-80",
    img: "/illustrations/02-journey.svg",
    imgWidth: 280,
  },
  {
    id: 3,
    type: "small" as const,
    title: "Todos os serviços que seu produto precisa",
    description: "Em um só lugar",
    className: "col-span-1 min-h-[280px]",
    imgClassName: "opacity-80",
    img: "/illustrations/03-modules.svg",
    imgWidth: 280,
  },
  {
    id: 4,
    type: "small" as const,
    title: "Tecnologia moderna e escalável para crescer sem limites",
    description: "Stack atualizado",
    className: "col-span-1 min-h-[280px]",
    imgClassName: "opacity-80",
    img: "/illustrations/04-stack.svg",
    imgWidth: 280,
  },
];
