export const GRID_ITEMS = [
  {
    id: 1,
    title: "Transformamos desafios complexos em produtos digitais elegantes",
    description: "Estúdio de produto completo",
    className: "lg:col-span-3 md:col-span-6 md:row-span-4 lg:min-h-[60vh]",
    imgClassName: "w-full h-full object-contain opacity-30",
    titleClassName: "justify-end",
    img: "/illustrations/01-studio.svg",
    imgWidth: 800,
    spareImg: "",
  },
  {
    id: 2,
    title: "Da descoberta ao lançamento — dominamos todo o ciclo de entrega",
    description: "Sem lacunas. Sem repassos.",
    className: "lg:col-span-2 md:col-span-3 md:row-span-2",
    imgClassName: "w-full h-full object-contain opacity-30",
    titleClassName: "justify-end",
    img: "/illustrations/02-journey.svg",
    imgWidth: 600,
    spareImg: "",
  },
  {
    id: 3,
    title: "Todos os serviços que seu produto precisa",
    description: "Em um só lugar",
    className: "lg:col-span-2 md:col-span-3 md:row-span-2",
    imgClassName: "w-full h-full object-contain opacity-30",
    titleClassName: "justify-end",
    img: "/illustrations/03-modules.svg",
    imgWidth: 600,
    spareImg: "",
  },
];
